
imports:
    - { resource: config.ini }

services:
    sitebuilder_filesystem:
        class: Inanimatt\SiteBuilder\TransformingFilesystem
        arguments: [@event_dispatcher]

    twig_markdown_transformer:
        class: Inanimatt\SiteBuilder\Transformer\TwigMarkdownTransformer
        arguments: [@markdown, @frontmatter_reader, @twig, %default_template%]
        tags:
            - { name: sitebuilder.transformer }

    twig_html_transformer:
        class: Inanimatt\SiteBuilder\Transformer\TwigHtmlTransformer
        arguments: [@frontmatter_reader, @twig, %default_template%]
        tags:
            - { name: sitebuilder.transformer }

    scss_transformer:
        class: Inanimatt\SiteBuilder\Transformer\SassTransformer
        arguments: [%sass_path%]
        tags:
            - { name: sitebuilder.transformer }

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    frontmatter_reader:
        class: Inanimatt\SiteBuilder\FrontmatterReader
        arguments: [@yaml]

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [%template_path%]

    twig:
        class: Twig_Environment
        arguments: [@twig.loader]

    yaml:
        class: Symfony\Component\Yaml\Parser

    markdown:
        class: dflydev\markdown\MarkdownExtraParser
