imports:
    - { resource: config.ini }
    
services:
    contentcollection:
        class: Inanimatt\SiteBuilder\ContentCollection\FileContentCollection
        arguments: [%content_dir%]
        calls:
            - [registerContentHandler, ["Inanimatt\\SiteBuilder\\ContentHandler\\PhpFileContentHandler", ["php"] ]]
            - [registerContentHandler, ["Inanimatt\\SiteBuilder\\ContentHandler\\MarkdownFileContentHandler", ["md", "markdown"]]]
            - [registerContentHandler, ["Inanimatt\\SiteBuilder\\ContentHandler\\CSSFileContentHandler", ["css"]]]

    serialiser:
        class: Inanimatt\SiteBuilder\Serialiser\FileSerialiser
        arguments: [%output_dir%]
    
    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [%template_path%]
    
    twig:
        class: Twig_Environment
        arguments: [@twig.loader]
    
    renderer.twig:
        class: Inanimatt\SiteBuilder\Renderer\TwigRenderer
        arguments: [@twig]

    renderer.php:
        class: Inanimatt\SiteBuilder\Renderer\PhpRenderer
        arguments: [%template_path%]
        
    finder:
        class: Symfony\Component\Finder\Finder
    
    yaml:
        class: Symfony\Component\Yaml\Parser
    
    markdown:
        class: dflydev\markdown\MarkdownParser

    sitebuilder:
        class: Inanimatt\SiteBuilder\SiteBuilder
        calls:
            - [setDefaultTemplate, [%default_template%]]
            - [setTemplatePath, [%template_path%]]
            - [registerRenderer, [@renderer.twig, ["twig"]]]
            - [registerRenderer, [@renderer.php, ["php"]]]

