
imports:
    - { resource: config.ini }

services:
    sitebuilder_filesystem:
        class: Inanimatt\SiteBuilder\TransformingFilesystem

    twig_markdown_transformer:
        class: Inanimatt\SiteBuilder\Transformer\TwigMarkdownTransformer
        arguments: [@markdown, @yaml, @twig, %default_template%]
        tags:
            - { name: sitebuilder.transformer }

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [%template_path%]

    twig:
        class: Twig_Environment
        arguments: [@twig.loader]

    yaml:
        class: Symfony\Component\Yaml\Parser

    markdown:
        class: dflydev\markdown\MarkdownExtraParser
