
imports:
    - { resource: config.ini }

services:
    sitebuilder_filesystem:
        class: Inanimatt\SiteBuilder\TransformingFilesystem
        calls:
            - [setLogger, [@monolog]]

    twig_markdown_transformer:
        class: Inanimatt\SiteBuilder\Transformer\TwigMarkdownTransformer
        arguments: [@markdown, @frontmatter_reader, @twig, %default_template%]
        tags:
            - { name: sitebuilder.transformer }

    twig_html_transformer:
        class: Inanimatt\SiteBuilder\Transformer\TwigHtmlTransformer
        arguments: [@frontmatter_reader, @twig, %default_template%]
        tags:
            - { name: sitebuilder.transformer }

    frontmatter_reader:
        class: Inanimatt\SiteBuilder\FrontmatterReader
        arguments: [@yaml]

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [%template_path%]

    twig:
        class: Twig_Environment
        arguments: [@twig.loader]

    yaml:
        class: Symfony\Component\Yaml\Parser

    markdown:
        class: dflydev\markdown\MarkdownExtraParser

    monolog:
        class: Monolog\Logger
        calls:
            - [pushHandler, [@monolog.streamhandler]]

    monolog.streamhandler:
        class: Monolog\Handler\StreamHandler
        arguments: ['sitebuilder.log', 100]
